# Generated by Django 3.0.5 on 2020-04-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DogTrain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='Pred_img'),
        ),
    ]
